[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dewrangle-python"
version = "1.0.0"
authors = [
  { name="Alex Sickler", email="sicklera@chop.edu" },
]
description = "Python API for connecting to Dewrangle"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
<<<<<<< HEAD
    "License :: OSI Approved :: Apache Software License",
=======
    "License :: OSI Approved :: Apache License",
>>>>>>> :package: create project metadata file
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/d3b-center/dewrangle-python"
"Bug Tracker" = "https://github.com/d3b-center/dewrangle-python/issues"
